image: "ruby:2.4"

renew-cert:
  stage: deploy
  only:
    - schedules
  script:
    - chmod +x certbot.sh
    - chmod +x dns.sh
    - ./renew.sh

before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j4 --path vendor

cache:
  paths:
    - vendor

stages:
#  - test
  - deploy

#lint:
#  stage: test
#  script:
#    - bundle exec rake lint
#  tags:
#    - ruby

pages:
  stage: deploy
  script:
    - bundle exec nanoc
  artifacts:
    paths:
      - public
  only:
    - master
