image: "ruby:2.4"

before_script:
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j4 --path vendor

cache:
  paths:
    - vendor

stages:
#  - test
  - deploy

#lint:
#  stage: test
#  script:
#    - bundle exec rake lint
#  tags:
#    - ruby

pages:
  stage: deploy
  script:
    - apt-get update -yqqq
    - bundle exec nanoc
  artifacts:
    paths:
      - public
  only:
    - master
