image: "ruby:2.4"

before_script:
  - apt-get update && apt-get install -y locales
  - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
  - locale-gen
  - export LC_ALL=en_US.UTF-8
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j4 --path vendor

cache:
  paths:
    - vendor

stages:
#  - test
  - deploy

#lint:
#  stage: test
#  script:
#    - bundle exec rake lint
#  tags:
#    - ruby

pages:
  stage: deploy
  script:
    - bundle exec nanoc
  artifacts:
    paths:
      - public
  only:
    - master
