source 'https://rubygems.org'

gem 'nanoc', '~> 4.0'
gem 'adsf'
gem 'kramdown'
gem 'nokogiri'
gem 'coderay'
gem 'rainpress'
gem 'mime-types'
gem 'builder'
gem 'pygments.rb'
gem 'stringex'
gem 'guard-nanoc'
gem 'html5small'
gem 'sass'
